language: java

# We use the default of Trusty, otherwise JDK 7 is not available!
dist: trusty

matrix:
  include:
    - jdk: openjdk7
    - jdk: openjdk8

    - os: osx
      osx_image: xcode9.3
      env: JAVA_HOME=$(/usr/libexec/java_home)


# We can skip the installation
# step, everything must run without
# preliminary installation.
install: true

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2

branches:
    except:
        - gh-pages

notifications:
    email:
        - khmarbaise@apache.org
